// Turns the original photos in /images-src into optimized, responsive WebP files in
// /public/images and writes src/data/images.js (sizes used by the <Photo> component).
//   npm i -D sharp   (one-off)   then   npm run images
// Add or replace a photo: put the PNG/JPG in images-src/ (file name = image name), run the command.
import { readdirSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join, parse } from "node:path";
import { fileURLToPath } from "node:url";

let sharp;
try { sharp = (await import("sharp")).default; } catch { console.error("Run `npm i -D sharp` first."); process.exit(1); }

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const src = join(root, "images-src");
const out = join(root, "public", "images");
mkdirSync(out, { recursive: true });

const WIDTHS = [480, 768, 1200, 1600];          // normal photos
const HERO_WIDTHS = [480, 750, 960, 1440, 1920]; // hero photos (shown full-screen)
const WIDE_WIDTHS = [768, 1200, 1600, 2200];     // wide banners (brand-*)
const data = {};

for (const file of readdirSync(src).filter((f) => /\.(png|jpe?g)$/i.test(f)).sort()) {
  const name = parse(file).name;
  const meta = await sharp(join(src, file)).metadata();
  const limit = name.startsWith("hero") ? HERO_WIDTHS : name.startsWith("brand") ? WIDE_WIDTHS : WIDTHS;
  const widths = [...new Set(limit.map((w) => Math.min(w, meta.width)))].sort((a, b) => a - b);
  for (const w of widths) {
    await sharp(join(src, file)).resize({ width: w }).webp({ quality: 76, effort: 5 }).toFile(join(out, `${name}-${w}.webp`));
  }
  data[name] = { w: meta.width, h: meta.height, widths };
  console.log(name.padEnd(28), `${meta.width}x${meta.height}`, widths.join(","));
}
writeFileSync(join(root, "src", "data", "images.js"),
  `// GENERATED by scripts/optimize-images.mjs — do not edit by hand.\nexport const IMAGES = ${JSON.stringify(data, null, 2)};\n`);
console.log("Done → public/images + src/data/images.js");
